if (!(Test-Path -LiteralPath "app\admin\all-changes\page.tsx")) { Write-Host "MISSING: app\admin\all-changes\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\change-requests\[id]\page.tsx")) { Write-Host "MISSING: app\admin\change-requests\[id]\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\change-requests\page.tsx")) { Write-Host "MISSING: app\admin\change-requests\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\dashboard\page.tsx")) { Write-Host "MISSING: app\admin\dashboard\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\demand-notices\page.tsx")) { Write-Host "MISSING: app\admin\demand-notices\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\document-archive\page.tsx")) { Write-Host "MISSING: app\admin\document-archive\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\operators\page.tsx")) { Write-Host "MISSING: app\admin\operators\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\shop-agreement-requests\[id]\page.tsx")) { Write-Host "MISSING: app\admin\shop-agreement-requests\[id]\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\shop-agreement-requests\page.tsx")) { Write-Host "MISSING: app\admin\shop-agreement-requests\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\shop-rate-report\page.tsx")) { Write-Host "MISSING: app\admin\shop-rate-report\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\shop-rental-applications\[id]\page.tsx")) { Write-Host "MISSING: app\admin\shop-rental-applications\[id]\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\shop-rental-applications\page.tsx")) { Write-Host "MISSING: app\admin\shop-rental-applications\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\trade-license-dashboard\page.tsx")) { Write-Host "MISSING: app\admin\trade-license-dashboard\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\trade-license-requests\[id]\page.tsx")) { Write-Host "MISSING: app\admin\trade-license-requests\[id]\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\admin\trade-license-requests\page.tsx")) { Write-Host "MISSING: app\admin\trade-license-requests\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\layout.tsx")) { Write-Host "MISSING: app\layout.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\login\page.tsx")) { Write-Host "MISSING: app\login\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\nagar-nigam-shops\apply\page.tsx")) { Write-Host "MISSING: app\nagar-nigam-shops\apply\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\nagar-nigam-shops\my-shop\page.tsx")) { Write-Host "MISSING: app\nagar-nigam-shops\my-shop\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\nagar-nigam-shops\page.tsx")) { Write-Host "MISSING: app\nagar-nigam-shops\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\operator\dashboard\page.tsx")) { Write-Host "MISSING: app\operator\dashboard\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\operator\property-tax\page.tsx")) { Write-Host "MISSING: app\operator\property-tax\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\operator\shops-hub\page.tsx")) { Write-Host "MISSING: app\operator\shops-hub\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\operator\shops\new-entry\page.tsx")) { Write-Host "MISSING: app\operator\shops\new-entry\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\operator\shops\page.tsx")) { Write-Host "MISSING: app\operator\shops\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\operator\trade-license\new-entry\page.tsx")) { Write-Host "MISSING: app\operator\trade-license\new-entry\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\operator\trade-license\page.tsx")) { Write-Host "MISSING: app\operator\trade-license\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\page.tsx")) { Write-Host "MISSING: app\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\portal-login\admin\forgot-password\page.tsx")) { Write-Host "MISSING: app\portal-login\admin\forgot-password\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\portal-login\admin\page.tsx")) { Write-Host "MISSING: app\portal-login\admin\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\portal-login\admin\reset-password\page.tsx")) { Write-Host "MISSING: app\portal-login\admin\reset-password\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\portal-login\operator\forgot-password\page.tsx")) { Write-Host "MISSING: app\portal-login\operator\forgot-password\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\portal-login\operator\page.tsx")) { Write-Host "MISSING: app\portal-login\operator\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\portal-login\operator\reset-password\page.tsx")) { Write-Host "MISSING: app\portal-login\operator\reset-password\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\portal-login\page.tsx")) { Write-Host "MISSING: app\portal-login\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\property-tax\page.tsx")) { Write-Host "MISSING: app\property-tax\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\property-tax\payment-return\page.tsx")) { Write-Host "MISSING: app\property-tax\payment-return\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\shop-rent\page.tsx")) { Write-Host "MISSING: app\shop-rent\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\trade-license\page.tsx")) { Write-Host "MISSING: app\trade-license\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\verify\agreement\[id]\page.tsx")) { Write-Host "MISSING: app\verify\agreement\[id]\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\verify\demand-notice\[demandNo]\page.tsx")) { Write-Host "MISSING: app\verify\demand-notice\[demandNo]\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\verify\receipt\[receiptNo]\page.tsx")) { Write-Host "MISSING: app\verify\receipt\[receiptNo]\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\verify\shop-demand\[demandNo]\page.tsx")) { Write-Host "MISSING: app\verify\shop-demand\[demandNo]\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\verify\shop-receipt\[receiptNo]\page.tsx")) { Write-Host "MISSING: app\verify\shop-receipt\[receiptNo]\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "app\verify\violation-notice\[id]\page.tsx")) { Write-Host "MISSING: app\verify\violation-notice\[id]\page.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\about.tsx")) { Write-Host "MISSING: components\about.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\admin-header.tsx")) { Write-Host "MISSING: components\admin-header.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\admin-login-client.tsx")) { Write-Host "MISSING: components\admin-login-client.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\admin\stage-badge.tsx")) { Write-Host "MISSING: components\admin\stage-badge.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\citizen-login-form.tsx")) { Write-Host "MISSING: components\citizen-login-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\contact.tsx")) { Write-Host "MISSING: components\contact.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\forgot-password-form.tsx")) { Write-Host "MISSING: components\forgot-password-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\hero.tsx")) { Write-Host "MISSING: components\hero.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator-header.tsx")) { Write-Host "MISSING: components\operator-header.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator-login-client.tsx")) { Write-Host "MISSING: components\operator-login-client.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator-task-card.tsx")) { Write-Host "MISSING: components\operator-task-card.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\demand-notice-reprint-view.tsx")) { Write-Host "MISSING: components\operator\demand-notice-reprint-view.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\document-verification-qr.tsx")) { Write-Host "MISSING: components\operator\document-verification-qr.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\entry-mode-launcher.tsx")) { Write-Host "MISSING: components\operator\entry-mode-launcher.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\financial-year-select.tsx")) { Write-Host "MISSING: components\operator\financial-year-select.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\floor-row.tsx")) { Write-Host "MISSING: components\operator\floor-row.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\notice-view.tsx")) { Write-Host "MISSING: components\operator\notice-view.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\operator-property-search.tsx")) { Write-Host "MISSING: components\operator\operator-property-search.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\partially-known-form.tsx")) { Write-Host "MISSING: components\operator\partially-known-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\payment-form.tsx")) { Write-Host "MISSING: components\operator\payment-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\phase-arv-row.tsx")) { Write-Host "MISSING: components\operator\phase-arv-row.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\property-document-history.tsx")) { Write-Host "MISSING: components\operator\property-document-history.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\property-editor-form.tsx")) { Write-Host "MISSING: components\operator\property-editor-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\receipt-reprint-view.tsx")) { Write-Host "MISSING: components\operator\receipt-reprint-view.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\receipt-view.tsx")) { Write-Host "MISSING: components\operator\receipt-view.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\shop-agreement-form.tsx")) { Write-Host "MISSING: components\operator\shop-agreement-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\shop-agreement-permit-view.tsx")) { Write-Host "MISSING: components\operator\shop-agreement-permit-view.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\shop-document-history.tsx")) { Write-Host "MISSING: components\operator\shop-document-history.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\shop-notice-view.tsx")) { Write-Host "MISSING: components\operator\shop-notice-view.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\shop-receipt-reprint-view.tsx")) { Write-Host "MISSING: components\operator\shop-receipt-reprint-view.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\shop-receipt-view.tsx")) { Write-Host "MISSING: components\operator\shop-receipt-view.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\shop-rent-payment-panel.tsx")) { Write-Host "MISSING: components\operator\shop-rent-payment-panel.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\shop-rental-application-form.tsx")) { Write-Host "MISSING: components\operator\shop-rental-application-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\shop-violation-notices.tsx")) { Write-Host "MISSING: components\operator\shop-violation-notices.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\operator\violation-notice-print-view.tsx")) { Write-Host "MISSING: components\operator\violation-notice-print-view.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\portal-branding-header.tsx")) { Write-Host "MISSING: components\portal-branding-header.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\portal-role-card.tsx")) { Write-Host "MISSING: components\portal-role-card.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\property-result-card.tsx")) { Write-Host "MISSING: components\property-result-card.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\property-search-form.tsx")) { Write-Host "MISSING: components\property-search-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\property-tax-search.tsx")) { Write-Host "MISSING: components\property-tax-search.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\reset-password-form.tsx")) { Write-Host "MISSING: components\reset-password-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\services.tsx")) { Write-Host "MISSING: components\services.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\shop-rent-result-card.tsx")) { Write-Host "MISSING: components\shop-rent-result-card.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\shop-rent-search-form.tsx")) { Write-Host "MISSING: components\shop-rent-search-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\shop-rent-search.tsx")) { Write-Host "MISSING: components\shop-rent-search.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\site-footer.tsx")) { Write-Host "MISSING: components\site-footer.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\site-header.tsx")) { Write-Host "MISSING: components\site-header.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\staff-login-form.tsx")) { Write-Host "MISSING: components\staff-login-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\stats.tsx")) { Write-Host "MISSING: components\stats.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\trade-license-application-form.tsx")) { Write-Host "MISSING: components\trade-license-application-form.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "components\verification-layout.tsx")) { Write-Host "MISSING: components\verification-layout.tsx" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\admin-api.ts")) { Write-Host "MISSING: lib\admin-api.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\admin-auth.ts")) { Write-Host "MISSING: lib\admin-auth.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\admin-shop-api.ts")) { Write-Host "MISSING: lib\admin-shop-api.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\admin-trade-license-api.ts")) { Write-Host "MISSING: lib\admin-trade-license-api.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\auth.ts")) { Write-Host "MISSING: lib\auth.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\config.ts")) { Write-Host "MISSING: lib\config.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\demand-notice-api.ts")) { Write-Host "MISSING: lib\demand-notice-api.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\nagar-nigam-shops.ts")) { Write-Host "MISSING: lib\nagar-nigam-shops.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\online-payment.ts")) { Write-Host "MISSING: lib\online-payment.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\operator-api.ts")) { Write-Host "MISSING: lib\operator-api.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\password-reset.ts")) { Write-Host "MISSING: lib\password-reset.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\payment-api.ts")) { Write-Host "MISSING: lib\payment-api.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\property-tax.ts")) { Write-Host "MISSING: lib\property-tax.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\shop-api.ts")) { Write-Host "MISSING: lib\shop-api.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\shop-rent-tax.ts")) { Write-Host "MISSING: lib\shop-rent-tax.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\trade-license-api.ts")) { Write-Host "MISSING: lib\trade-license-api.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\use-admin-guard.ts")) { Write-Host "MISSING: lib\use-admin-guard.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\use-operator-guard.ts")) { Write-Host "MISSING: lib\use-operator-guard.ts" -ForegroundColor Red }
if (!(Test-Path -LiteralPath "lib\verify-api.ts")) { Write-Host "MISSING: lib\verify-api.ts" -ForegroundColor Red }