if (!(Test-Path "scripts\create-admin.ts")) { Write-Host "MISSING: scripts\create-admin.ts" -ForegroundColor Red }
if (!(Test-Path "scripts\import-stalls.ts")) { Write-Host "MISSING: scripts\import-stalls.ts" -ForegroundColor Red }
if (!(Test-Path "scripts\migrate-from-csv.ts")) { Write-Host "MISSING: scripts\migrate-from-csv.ts" -ForegroundColor Red }
if (!(Test-Path "scripts\migrate-from-sheets.ts")) { Write-Host "MISSING: scripts\migrate-from-sheets.ts" -ForegroundColor Red }
if (!(Test-Path "scripts\reset-admin-password.ts")) { Write-Host "MISSING: scripts\reset-admin-password.ts" -ForegroundColor Red }
if (!(Test-Path "scripts\reset-operator-password.ts")) { Write-Host "MISSING: scripts\reset-operator-password.ts" -ForegroundColor Red }
if (!(Test-Path "scripts\run-migrations.ts")) { Write-Host "MISSING: scripts\run-migrations.ts" -ForegroundColor Red }
if (!(Test-Path "scripts\set-admin-email.ts")) { Write-Host "MISSING: scripts\set-admin-email.ts" -ForegroundColor Red }
if (!(Test-Path "scripts\set-operator-email.ts")) { Write-Host "MISSING: scripts\set-operator-email.ts" -ForegroundColor Red }
if (!(Test-Path "src\app.ts")) { Write-Host "MISSING: src\app.ts" -ForegroundColor Red }
if (!(Test-Path "src\config\db.ts")) { Write-Host "MISSING: src\config\db.ts" -ForegroundColor Red }
if (!(Test-Path "src\config\env.ts")) { Write-Host "MISSING: src\config\env.ts" -ForegroundColor Red }
if (!(Test-Path "src\constants\marketCodes.ts")) { Write-Host "MISSING: src\constants\marketCodes.ts" -ForegroundColor Red }
if (!(Test-Path "src\constants\taxRates.ts")) { Write-Host "MISSING: src\constants\taxRates.ts" -ForegroundColor Red }
if (!(Test-Path "src\constants\tradeLicenseDocuments.ts")) { Write-Host "MISSING: src\constants\tradeLicenseDocuments.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\adminAuth.controller.ts")) { Write-Host "MISSING: src\controllers\adminAuth.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\adminOperators.controller.ts")) { Write-Host "MISSING: src\controllers\adminOperators.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\adminTaxHistory.controller.ts")) { Write-Host "MISSING: src\controllers\adminTaxHistory.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\auth.controller.ts")) { Write-Host "MISSING: src\controllers\auth.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\changeRequest.controller.ts")) { Write-Host "MISSING: src\controllers\changeRequest.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\demandNotice.controller.ts")) { Write-Host "MISSING: src\controllers\demandNotice.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\export.controller.ts")) { Write-Host "MISSING: src\controllers\export.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\formOptions.controller.ts")) { Write-Host "MISSING: src\controllers\formOptions.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\newEntry.controller.ts")) { Write-Host "MISSING: src\controllers\newEntry.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\onlinePayment.controller.ts")) { Write-Host "MISSING: src\controllers\onlinePayment.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\passwordReset.controller.ts")) { Write-Host "MISSING: src\controllers\passwordReset.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\payment.controller.ts")) { Write-Host "MISSING: src\controllers\payment.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\property.controller.ts")) { Write-Host "MISSING: src\controllers\property.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\propertySave.controller.ts")) { Write-Host "MISSING: src\controllers\propertySave.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\shop.controller.ts")) { Write-Host "MISSING: src\controllers\shop.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\shopAgreement.controller.ts")) { Write-Host "MISSING: src\controllers\shopAgreement.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\shopRent.controller.ts")) { Write-Host "MISSING: src\controllers\shopRent.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\shopRentalApplication.controller.ts")) { Write-Host "MISSING: src\controllers\shopRentalApplication.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\shopViolationNotice.controller.ts")) { Write-Host "MISSING: src\controllers\shopViolationNotice.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\taxPreview.controller.ts")) { Write-Host "MISSING: src\controllers\taxPreview.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\tradeLicenseApplication.controller.ts")) { Write-Host "MISSING: src\controllers\tradeLicenseApplication.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\controllers\verify.controller.ts")) { Write-Host "MISSING: src\controllers\verify.controller.ts" -ForegroundColor Red }
if (!(Test-Path "src\middleware\asyncHandler.ts")) { Write-Host "MISSING: src\middleware\asyncHandler.ts" -ForegroundColor Red }
if (!(Test-Path "src\middleware\errorHandler.ts")) { Write-Host "MISSING: src\middleware\errorHandler.ts" -ForegroundColor Red }
if (!(Test-Path "src\middleware\loginRateLimiter.ts")) { Write-Host "MISSING: src\middleware\loginRateLimiter.ts" -ForegroundColor Red }
if (!(Test-Path "src\middleware\requireAdmin.ts")) { Write-Host "MISSING: src\middleware\requireAdmin.ts" -ForegroundColor Red }
if (!(Test-Path "src\middleware\requireOperator.ts")) { Write-Host "MISSING: src\middleware\requireOperator.ts" -ForegroundColor Red }
if (!(Test-Path "src\middleware\requireOperatorOrAdmin.ts")) { Write-Host "MISSING: src\middleware\requireOperatorOrAdmin.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\admin.repository.ts")) { Write-Host "MISSING: src\repositories\admin.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\changeRequest.repository.ts")) { Write-Host "MISSING: src\repositories\changeRequest.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\demandNotice.repository.ts")) { Write-Host "MISSING: src\repositories\demandNotice.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\onlinePayment.repository.ts")) { Write-Host "MISSING: src\repositories\onlinePayment.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\operator.repository.ts")) { Write-Host "MISSING: src\repositories\operator.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\passwordReset.repository.ts")) { Write-Host "MISSING: src\repositories\passwordReset.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\payment.repository.ts")) { Write-Host "MISSING: src\repositories\payment.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\property.repository.ts")) { Write-Host "MISSING: src\repositories\property.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\propertySave.repository.ts")) { Write-Host "MISSING: src\repositories\propertySave.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\shop.repository.ts")) { Write-Host "MISSING: src\repositories\shop.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\shopAgreementChangeRequest.repository.ts")) { Write-Host "MISSING: src\repositories\shopAgreementChangeRequest.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\shopRent.repository.ts")) { Write-Host "MISSING: src\repositories\shopRent.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\shopRentalApplication.repository.ts")) { Write-Host "MISSING: src\repositories\shopRentalApplication.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\shopViolationNotice.repository.ts")) { Write-Host "MISSING: src\repositories\shopViolationNotice.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\repositories\tradeLicenseApplication.repository.ts")) { Write-Host "MISSING: src\repositories\tradeLicenseApplication.repository.ts" -ForegroundColor Red }
if (!(Test-Path "src\routes\admin.routes.ts")) { Write-Host "MISSING: src\routes\admin.routes.ts" -ForegroundColor Red }
if (!(Test-Path "src\routes\adminAuth.routes.ts")) { Write-Host "MISSING: src\routes\adminAuth.routes.ts" -ForegroundColor Red }
if (!(Test-Path "src\routes\auth.routes.ts")) { Write-Host "MISSING: src\routes\auth.routes.ts" -ForegroundColor Red }
if (!(Test-Path "src\routes\index.ts")) { Write-Host "MISSING: src\routes\index.ts" -ForegroundColor Red }
if (!(Test-Path "src\routes\payments.routes.ts")) { Write-Host "MISSING: src\routes\payments.routes.ts" -ForegroundColor Red }
if (!(Test-Path "src\routes\property.routes.ts")) { Write-Host "MISSING: src\routes\property.routes.ts" -ForegroundColor Red }
if (!(Test-Path "src\routes\shop.routes.ts")) { Write-Host "MISSING: src\routes\shop.routes.ts" -ForegroundColor Red }
if (!(Test-Path "src\routes\shopRentalApplication.routes.ts")) { Write-Host "MISSING: src\routes\shopRentalApplication.routes.ts" -ForegroundColor Red }
if (!(Test-Path "src\routes\tradeLicenseApplication.routes.ts")) { Write-Host "MISSING: src\routes\tradeLicenseApplication.routes.ts" -ForegroundColor Red }
if (!(Test-Path "src\routes\verify.routes.ts")) { Write-Host "MISSING: src\routes\verify.routes.ts" -ForegroundColor Red }
if (!(Test-Path "src\server.ts")) { Write-Host "MISSING: src\server.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\adminAuth.service.ts")) { Write-Host "MISSING: src\services\adminAuth.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\arrears.service.ts")) { Write-Host "MISSING: src\services\arrears.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\auth.service.ts")) { Write-Host "MISSING: src\services\auth.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\automaticTaxHistory.service.ts")) { Write-Host "MISSING: src\services\automaticTaxHistory.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\changeClassification.service.ts")) { Write-Host "MISSING: src\services\changeClassification.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\changeRequest.service.ts")) { Write-Host "MISSING: src\services\changeRequest.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\charges.service.ts")) { Write-Host "MISSING: src\services\charges.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\computeStageYears.service.ts")) { Write-Host "MISSING: src\services\computeStageYears.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\demandNotice.service.ts")) { Write-Host "MISSING: src\services\demandNotice.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\email.service.ts")) { Write-Host "MISSING: src\services\email.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\export.service.ts")) { Write-Host "MISSING: src\services\export.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\holdingNumberSeries.service.ts")) { Write-Host "MISSING: src\services\holdingNumberSeries.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\newEntry.service.ts")) { Write-Host "MISSING: src\services\newEntry.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\onlinePayment.service.ts")) { Write-Host "MISSING: src\services\onlinePayment.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\partiallyKnown.service.ts")) { Write-Host "MISSING: src\services\partiallyKnown.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\passwordReset.service.ts")) { Write-Host "MISSING: src\services\passwordReset.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\payment.service.ts")) { Write-Host "MISSING: src\services\payment.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\property.service.ts")) { Write-Host "MISSING: src\services\property.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\propertySave.service.ts")) { Write-Host "MISSING: src\services\propertySave.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\rentCalculation.service.ts")) { Write-Host "MISSING: src\services\rentCalculation.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\shopAgreement.service.ts")) { Write-Host "MISSING: src\services\shopAgreement.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\shopAgreementClassification.service.ts")) { Write-Host "MISSING: src\services\shopAgreementClassification.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\shopNumbering.service.ts")) { Write-Host "MISSING: src\services\shopNumbering.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\shopRentDemand.service.ts")) { Write-Host "MISSING: src\services\shopRentDemand.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\shopRentPayment.service.ts")) { Write-Host "MISSING: src\services\shopRentPayment.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\shopRentalApplication.service.ts")) { Write-Host "MISSING: src\services\shopRentalApplication.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\shopReporting.service.ts")) { Write-Host "MISSING: src\services\shopReporting.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\shopSearch.service.ts")) { Write-Host "MISSING: src\services\shopSearch.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\shopViolationNotice.service.ts")) { Write-Host "MISSING: src\services\shopViolationNotice.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\taxCalculation.service.ts")) { Write-Host "MISSING: src\services\taxCalculation.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\taxPreview.service.ts")) { Write-Host "MISSING: src\services\taxPreview.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\services\tradeLicenseApplication.service.ts")) { Write-Host "MISSING: src\services\tradeLicenseApplication.service.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\admin.types.ts")) { Write-Host "MISSING: src\types\admin.types.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\auth.types.ts")) { Write-Host "MISSING: src\types\auth.types.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\changeRequest.types.ts")) { Write-Host "MISSING: src\types\changeRequest.types.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\demandNotice.types.ts")) { Write-Host "MISSING: src\types\demandNotice.types.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\express.d.ts")) { Write-Host "MISSING: src\types\express.d.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\newEntry.types.ts")) { Write-Host "MISSING: src\types\newEntry.types.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\payment.types.ts")) { Write-Host "MISSING: src\types\payment.types.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\property.types.ts")) { Write-Host "MISSING: src\types\property.types.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\propertySave.types.ts")) { Write-Host "MISSING: src\types\propertySave.types.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\shop.types.ts")) { Write-Host "MISSING: src\types\shop.types.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\taxPreview.types.ts")) { Write-Host "MISSING: src\types\taxPreview.types.ts" -ForegroundColor Red }
if (!(Test-Path "src\types\tradeLicense.types.ts")) { Write-Host "MISSING: src\types\tradeLicense.types.ts" -ForegroundColor Red }
if (!(Test-Path "src\utils\ApiError.ts")) { Write-Host "MISSING: src\utils\ApiError.ts" -ForegroundColor Red }
if (!(Test-Path "src\utils\amountInWords.ts")) { Write-Host "MISSING: src\utils\amountInWords.ts" -ForegroundColor Red }
if (!(Test-Path "src\utils\assessmentYear.ts")) { Write-Host "MISSING: src\utils\assessmentYear.ts" -ForegroundColor Red }
if (!(Test-Path "src\utils\num.ts")) { Write-Host "MISSING: src\utils\num.ts" -ForegroundColor Red }
if (!(Test-Path "src\utils\verificationSignature.ts")) { Write-Host "MISSING: src\utils\verificationSignature.ts" -ForegroundColor Red }
if (!(Test-Path "src\utils\yearMonth.ts")) { Write-Host "MISSING: src\utils\yearMonth.ts" -ForegroundColor Red }